import Head from 'next/head'
import Toolbar from '../components/Toolbar'
import Navbar from '../components/Navbar'
import SubNav from '../components/SubNav'
import MacroCard from '../components/Macrocard'
import CardSection from '../components/CardSection'
import styles from "../styles/Home.module.scss"

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Sempre Domenica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MacroCard />
      <CardSection />
    </div>
  )
}
